### ISSUE TITLE
URL of filter doesnt work

### ISSUE THREAD

**Issue by mischabraam** [EmicoEcommerce/Magento2AttributeLandingTweakwise#4]
When I have an active page for an attribute filter, the URL for removing the filter seems to be incorrect. In other words, when I filter the products on a category page on a product attribute, I can't remove that filter.

See screenshot for an active implementation. You'll see that the URL for removing the filter equals the current URL. When clicking the remove filter button, nothing happens.

![Screenshot_2022-11-24_at_14_53_39](https://user-images.githubusercontent.com/19824986/203801556-ae1628ed-c983-4f12-ac83-e486ce135d36.png)

**Comment by ahuininga-orisha** [comment]
@mischabraam What is the expected way it should work in your opinion? Actually remove the default selected filters from an ALP or should it not be possible to remove it?

I'll discuss this internally to see if we can find an proper solution for this.

The problem is that the filters aren't removed because they are re-added by the ALP and not part of the url.

1. Should the default filters for an ALP be removable?
2. Can the url for an ALP be the same with or without 'default selected filters'? Or should it be an different url?
3. If you click 'remove all filters' do the 'default selected filters' get removed even if the 'hide selected filters' option is on?

**Comment by mischabraam** [comment]
About your first option:
It should behave like "normal" filters. For users visiting the webshop there is no distinction between a normal filtered POP or an ALP, except that an ALP displays extra information. Besides that there shouldn't be any difference. So, I suggest the 'X' should remove the filter (only that one) like Magento does with any other filter you remove.

The other options: I'm not sure.

**Comment by ahuininga-orisha** [comment]
@mischabraam I had the same problem as you at first (can't remove the filter). But i had an mistake in my filter configuration. I've used the filter Sale (with an capital letter) instead of sale. Once i changed that. The clear, and remove filter options where working for me. They redirect you to the category page.

Can you check if the filter attributes of the ALP are correct? They are case sensitive. For my sale filter, the name of the filter was in lowercase, and for the value (Yes) the first letter was an capital. So for you example, i think the filter name should be 'geslacht' (lowercase) and the value 'Jongen'

An easy way to test if the filter attributes are correct is to see if the filter is completly hidden if you select 'hide filters'. Then the selected filter should not be visible anyware (active filters, url, filter menu)

**Comment by mischabraam** [comment]
Haha, yes, that worked. Thank you very much.
